In [1]:

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import production


In [2]:
np.random.seed(100)

In [3]:
# The number of firms
J = 2


# The number of time periods
T = 3

In [37]:
df_0 = pd.read_csv('/Users/popovici/Desktop/Thesis/markdown_estimation/data/market_100.csv')

shares =np.reshape(np.array(df_0['mshare']), (99, 10)).T
print(shares[:,0])


p1 = (np.sum(shares[:,0])*500)
print(p1)

p2 = (1 - np.sum(shares[:, 0]))*500
print(p2)

print(p1 + p2)



[0.07792925 0.11167755 0.10594724 0.08385975 0.12890967 0.09895551
 0.07281758 0.08179806 0.10041013 0.09662901]
479.4668699797625
20.53313002023749
500.0


In [4]:
# Getting the exact number of periods and stuff also from the dataframe for the market based approach 
df = pd.read_csv('/Users/popovici/Desktop/Thesis/markdown_estimation/data/market_100.csv').head(T*10)
df_grouped = df.groupby('time').head(J)
print(df_grouped)

       price      cost  product  time      Car1      Car2    mshare   profits  \
0   3.695253  1.415698        1     1  5.543405  5.891322  0.078804  0.179638   
1   3.756714  1.447384        2     1  5.278369  5.209202  0.107499  0.248250   
10  4.001494  1.413811        1     2  5.543405  5.891322  0.079771  0.206423   
11  4.140559  1.500000        2     2  5.278369  5.209202  0.105996  0.279890   
20  3.714313  1.434079        1     3  5.543405  5.891322  0.076635  0.174747   
21  3.753785  1.457664        2     3  5.278369  5.209202  0.105537  0.242325   

     markups  
0   1.610199  
1   1.595521  
10  1.830290  
11  1.760373  
20  1.590035  
21  1.575205  


In [5]:

true_price = np.reshape(np.array(df_grouped['price']), (T, J)).T
print(true_price)

true_share = np.reshape(np.array(df_grouped['mshare']), (T, J)).T
print(true_share)

true_markup = np.reshape(np.array(df_grouped['markups']), (T, J)).T

print(true_markup)

[[3.69525344 4.00149428 3.71431331]
 [3.75671434 4.14055935 3.75378478]]
[[0.07880396 0.07977116 0.07663546]
 [0.10749874 0.10599642 0.10553664]]
[[1.61019918 1.83029012 1.59003451]
 [1.59552078 1.7603729  1.57520492]]


In [6]:
# The vector of parameters for the production function 
beta_production = np.array([1, 0.3, 0.7])
# The coeff in the production function stuff 

# Markov Chain memory
alpha = 0.7

# Productivity distribution 
mean_omega = 1
sigma_omega = 0.1


# Capital distribution
mean_capital = 1
sigma_capital = 0.5
delta = 0.05


# Errors important for the econometric analysis but not important for the DGP
eta_labor = np.random.normal(0, 0.2, (J, T))
eta_production = np.random.normal(0, 0.2, (J, T))


# Some initial guess for the wage
wage = np.ones((J, T))/2


In [7]:
productivity, capital, investment = production.formation_capital_investment(J, T, 
                                                                            alpha, mean_omega, sigma_omega, mean_capital,
                                                                            sigma_capital, delta)
print(productivity)
print(capital)
print(investment)

[[0.94164049 0.60602031 0.38040065]
 [1.08168471 0.86015256 0.49027497]]
[[1.3363604  1.46219751 1.55080965]
 [0.94779443 1.0503159  1.14065909]]
[[0.19265513 0.16172201 0.13653338]
 [0.1499112  0.14285899 0.11295661]]


In [8]:
print(np.log(true_share*500))

[[3.67381607 3.68601488 3.64591266]
 [3.98433194 3.97025811 3.96591098]]


In [9]:
# Optimal labor at this value is (in equilibiurm and as given by the market quantitiy)
# Using this impliees that the model is agnostic to the wage when choosing labor 
# The cost already determined how much to produce so maybe there is not much else that can be done here 
L = (np.log(true_share[:, 0]*500) - beta_production[2]*capital[:, 0])/beta_production[1]
print(L)
 

[ 9.12787929 11.06958614]


In [10]:
L, Y = production.formation_labor_production_log(J, T, capital, beta_production, true_price,
                                                  wage, productivity, eta_labor, eta_production)
# At the prices in the market and an initial value of the wage this are going to be the optimal prices 

[[4.74766172 0.         0.        ]
 [5.01053244 0.         0.        ]]
[[4.34562723 0.         0.        ]
 [4.29930083 0.         0.        ]]
1
2
[[4.74766172 5.10562412 4.99706109]
 [5.01053244 5.28806159 4.57645583]]
[[4.34562723 3.94723714 3.92718657]
 [4.29930083 4.09018678 3.74870578]]
[[3.67381607 3.68601488 3.64591266]
 [3.98433194 3.97025811 3.96591098]]


In [ ]:
def labor_from

In [11]:
# Getting toy level mardown: 
markup_production_1 = np.zeros((J, T))
markup_production_2 = np.zeros((J, T))


markup_production_1[:, 0] = (beta_production[1] * true_price[:, 0]*np.log(true_share[:, 0]*500))/(wage[:, 0]*0.1*L)

print(markup_production_1)
print(true_markup)

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 