In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from market import IntegratedMarketModel

In [2]:
from matplotlib import rc
rc('font', **{'family': 'serif', 'serif': ['Computer Modern']})
rc('text', usetex=True)

In [3]:
n_firms = 10 
n_consumers = 10000
n_chars = 2
T = 100

In [4]:
# Instead of this it can also be posibile to just plug in the model estimation from seed 100 directly from 
# the created datasets
seed = 4
df= pd.read_csv(f'../data/market_integrates_{seed}.csv')
print(df)


model_true = IntegratedMarketModel(
        n_firms, 
        n_consumers, 
        n_chars, 
        T, 
        seed=seed
    )
model_true.demand_side_optimisation()


     market_ids  firm_ids  characteristic1  characteristic2    prices  \
0             1         1         4.582194         1.697368  4.572060   
1             1         2         4.904177         3.831666  4.295544   
2             1         3         1.272172         3.596674  4.809153   
3             1         4         4.533492         1.943444  4.598940   
4             1         5         3.396054         4.213493  4.469387   
..          ...       ...              ...              ...       ...   
995         100         6         1.712343         4.454706  4.589379   
996         100         7         3.032257         5.808905  4.213014   
997         100         8         5.301537         5.261936  3.829661   
998         100         9         4.131692         5.935763  4.236585   
999         100        10         2.749951         5.557247  4.592509   

     marginal_cost    shares   profits   markups  e_quantity    capital  \
0         3.793774  0.001272  0.000990  1.205148

In [13]:
# Create the instrument matrix using the results in the model
def create_instrument_matrix(df):
    create_instrument_matrix_1 = np.column_stack((df['characteristic1'], df['characteristic2']))
    create_instrument_matrix_2 = np.column_stack((create_instrument_matrix_1, df['labor']))
    instrument_matrix = np.column_stack((create_instrument_matrix_2,df['capital']))

    return instrument_matrix

In [15]:
Z = create_instrument_matrix(df)
print(Z.shape)

(1000, 4)


In [25]:
# Try to estimate the linear parameters from beta 

def estimate_linear_param(df):
    # The mean utility vector should be composed also of 
    instruments = create_instrument_matrix(df)
    car_bind = np.column_stack((df['characteristic1'], df['characteristic2']))
    XP = np.column_stack((car_bind, df['prices']))
    cross_prod = np.matmul(XP.T, instruments)
    print(XP.shape)
    print(instruments.shape)
    print(cross_prod)



    

In [26]:
try1 = estimate_linear_param(df)

(1000, 3)
(1000, 4)
[[14361.77065036 14720.95875337  5348.81457428 56389.99304724]
 [14720.95875337 19942.13119001  6132.83331068 64084.55543901]
 [15336.02097613 18331.52032029  6910.54142712 68467.07690884]]
